apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: node
build:
  artifacts:
    - image: package-json-image 
      context: .
manifests:
  rawYaml:
    - deployment.yaml
portForward:
  - resourceType: service
    resourceName: package-json-image
    port: 4444
deploy:
  kubectl: {}