/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export function readFileAsync(path: string): Promise<Buffer>
export function busyLoopRs(n: number): number
export function callWithOne(n: number, func: (arg0: number) => number): number
