apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: go
build:
  # platforms: ["linux/arm64"]
  artifacts:
    - image: producer
      custom:
        buildCommand: |
          make image/build/producer
    - image: consumer
      custom:
        buildCommand: |
          make image/build/consumer
    - image: consumer-py
      sync:
        infer:
          - 'python/*.py'
manifests:
  rawYaml:
    - k8s/deployment.yml
    - k8s/configmap.yml
    - k8s/service.yml
    #    - k8s/kafka-resources.yml

