apiVersion: apps/v1
kind: Deployment
metadata:
  name: keel-demo
  namespace: keel-demo
  labels:
    app: keel-demo
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keel-demo
  template:
    metadata:
      labels:
        app: keel-demo
    spec:
      containers:
        - name: app
          image: docker.io/unknowntpo/keel-test:latest
          imagePullPolicy: Always
          env:
            - name: APP_MESSAGE
              value: "Served by Keel-managed deployment"
            - name: IMAGE_TAG
              value: "latest"
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
