# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  # config.vm.box = "bento/ubuntu-18.04"
  # config.vm.box_version = "7.0.18"
  config.vm.hostname = 'k8s-dev'
  config.vm.define vm_name = 'k8s'

  config.vm.network :private_network, ip: "172.17.8.111"
  config.vm.provider "parallels" do |v|
    v.memory = 8192
    v.cpus = 4
  end
end
