[package]
name = "tracing_subscriber_example"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing-subscriber = "0.3.19"
log = "0.4.22"
tracing = "0.1.41"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "my_benchmark"
harness = false
