apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: disk
provisioner: kubernetes.io/no-provisioner
parameters:
  type: pd-standard

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: disk
  resources:
    requests:
      storage: 3Gi


