---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-rs-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-rs-controller
rules:
- apiGroups: ["example.com"]
  resources: ["myresources"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-rs-controller
subjects:
- kind: ServiceAccount
  name: kube-rs-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: kube-rs-controller
  apiGroup: rbac.authorization.k8s.io
