/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Library {
  def someLibraryMethod(): Boolean = true
  def stringIntMapToStringStringMap(m: Map[String,Int]): Map[String,String] = {
    m.map {case(k,v)=> k -> v.toString}
  }
}
