version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: jcasbin_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jcasbin_demo
      MYSQL_USER: jcasbin
      MYSQL_PASSWORD: jcasbin123
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: