/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app

import org.apache.commons.text.WordUtils
import org.example.Splitter.Splitter

object App {
  def main(args: Array[String]): Unit = {
    val tokens: java.util.List[String] = Splitter.split(MessageUtils.getMessage())
    println(tokens)
  }
}
