/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void testStreamInt() {
        List<Integer> numbers = Arrays.asList(1, 3, 4, 5, 6, 7, 8);
        var evenNums = numbers.stream().filter(e -> e % 2 != 0).collect(Collectors.toList());
        assertEquals(evenNums, Arrays.asList(1, 3, 5, 7));
    }

    @Test
    void testGetMaxAge() {
        List<Integer> ages = Arrays.asList(12, 3, 4, 50, 60, 7, 18);
        Integer maxAge = ages.stream().reduce(0, (a, b) -> a > b ? a : b);
        assertEquals(60, maxAge);
    }
}
