/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.leetcode;

import static org.junit.Assert.assertArrayEquals;

import java.util.Arrays;
import java.util.Collection;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

@RunWith(Parameterized.class)
public class TwoSumTest {
  private final TwoSum twoSum = new TwoSum();
  private final int[] nums;
  private final int target;
  private final int[] expected;

  public TwoSumTest(int[] nums, int target, int[] expected) {
    this.nums = nums;
    this.target = target;
    this.expected = expected;
  }

  @Parameterized.Parameters
  public static Collection<Object[]> testData() {
    return Arrays.asList(
        new Object[][] {{new int[] {2, 7, 11, 15}, 9, new int[] {0, 1}},
                        {new int[] {3, 2, 4}, 6, new int[] {1, 2}},
                        {new int[] {3, 3}, 6, new int[] {0, 1}},
                        {new int[] {}, 5, new int[0]},
                        {new int[] {1, 2, 3, 4, 5}, 10, new int[0]}});
  }

  @Test
  public void testTwoSum() {
    TwoSum twoSum = new TwoSum();
    assertArrayEquals(expected, twoSum.twoSum(nums, target));
  }
}