FROM debian:bullseye-20250407
# FROM debian:stable


WORKDIR /root

# RUN apt-get update || (apt-get clean && apt-get update)

RUN apt-get update



# RUN apt-get -q update && \
#    apt-get install -y -q python python3 gcc mariadb-server vim curl wget openjdk-11-jdk git procps && \
#Jk    rm -rf /var/lib/apt/lists/*


