/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Map<Integer, Integer> map = new HashMap<>();
        map.put(1, 2);
        map.put(2, 3);
        map.put(3, 4);

        final Optional<Integer> max = map.values().stream().max(Integer::compareTo);;
    }
}
