apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: producer
          # TODO: replace to image name in Dockerfile 
          # image: golang:1.20.4-alpine3.18
          image: producer
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 4000

apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: consumer
          # TODO: replace to image name in Dockerfile 
          # image: golang:1.20.4-alpine3.18
          image: consumer
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 4000
