apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          # TODO: replace to image name in Dockerfile 
          # image: golang:1.20.4-alpine3.18
          image: producer
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 4000
          env:
            - name: KAFKA_BROKERS # Notice that the case is different here
              valueFrom:
                configMapKeyRef:
                  name: kafka-client-config
                  key: KAFKA_BROKERS # The key to fetch.

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 0
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          # TODO: replace to image name in Dockerfile 
          # image: golang:1.20.4-alpine3.18
          image: consumer
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 4000
          env:
            - name: KAFKA_BROKERS # Notice that the case is different here
              valueFrom:
                configMapKeyRef:
                  name: kafka-client-config
                  key: KAFKA_BROKERS # The key to fetch.

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-py
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer-py
          # TODO: replace to image name in Dockerfile 
          # image: golang:1.20.4-alpine3.18
          image: consumer-py
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 4000
          env:
            - name: KAFKA_BROKERS # Notice that the case is different here
              valueFrom:
                configMapKeyRef:
                  name: kafka-client-config
                  key: KAFKA_BROKERS # The key to fetch.
