apiVersion: v1
kind: Service
metadata:
  name: producer-svc
spec:
  type: NodePort
  selector:
    app: producer
  ports:
  - port: 3000
    targetPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: consumer-svc
spec:
  type: NodePort
  selector:
    app: consumer
  ports:
  - port: 3000
    targetPort: 4000


