/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.List;

public class App {
    private static List<DemoObject> objests;

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        objests = new ArrayList<DemoObject>();
        System.out.println(new App().getGreeting());
        while (true) {
            DemoObject obj = new DemoObject();
            objests.add(obj);
        }
    }
}
