version: '3.7'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dvdrental
    ports:
      - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dvdrental.zip:/tmp/dvdrental.zip
      #      - pg_restore -U $POSTGRES_USER -d /tmp/dvdrental.zip
    networks:
      - pg_network

  restore:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dvdrental
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        cat > /wait-for-postgres.sh << EOF
        #!/bin/sh
        while true; do
          if pg_isready -h postgres -U $$POSTGRES_USER; then
            echo "PostgreSQL is ready!"
            break
          else
            echo "PostgreSQL is not ready. Waiting..."
            sleep 1
          fi
        done
        EOF
        chmod +x /wait-for-postgres.sh
        /wait-for-postgres.sh

        PGPASSWORD=$$POSTGRES_PASSWORD pg_restore -h postgres -U $$POSTGRES_USER -v -d dvdrental /tmp/dvdrental/

        echo "Migration completed."
    volumes:
      - ./dvdrental:/tmp/dvdrental

    networks:
      - pg_network


networks:
  pg_network:

volumes:
  pgdata:
