# Use the Go base image
FROM golang:1.20-buster

# Set the working directory
WORKDIR /app

# Copy the source code
COPY go.* .
COPY ./manager .

# Build the worker service
RUN go build -o manager .

# Start the worker service
CMD ["./manager"]