/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package field_validator;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        User user = new User("john_doe", "john@example.com");
        try {
            boolean isValid = FieldValidator.validate(user);
            System.out.println("User is valid: " + isValid);
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }

        User invalidUser = new User("", "");
        try {
            boolean isValid = FieldValidator.validate(invalidUser);
            System.out.println("Invalid user is valid: " + isValid);
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
    }
}
