/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
/** module registration is done by the runtime, no need to explicitly do it now. */
export function fibonacci(n: number): number
