version: '3'

services:
  db0:
    image: postgres:9.6
    restart: always
    ports:
      - "5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: postgres
  db1:
    image: postgres:14
    restart: always
    ports:
      - "5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: postgres
volumes:
  pg-data:
  link-data:
