/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap;

import java.util.HashMap;

public class App {
    public String getGreeting() {
        HashMap<String, Integer> lang = new HashMap<>();
        lang.put("java", 8);
        lang.put("go", 10);
        return lang.toString();
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
