/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InterruptedException, ExecutionException {
        System.out.println(new App().getGreeting());
        Calculator cal = new Calculator();
        int x = 1, y = 2;
        Future<Integer> future = cal.addAsync(x, y);
        while (!future.isDone()) {
            System.out.println("Waiting for result...");
            Thread.sleep(300);
        }
        System.out.printf("%d + %d = %d%n", x, y, future.get());
    }
}
