/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.Assert.assertEquals
import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends AnyFunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()

    assert(library.someLibraryMethod())
  }

  test("stringIntMapToStringStringMap") {
    def library = new Library()

    def testM = Map("hello" -> 0, "world" -> 1)

    assertEquals(Map("hello" -> "0", "world" -> "1"), library.stringIntMapToStringStringMap(testM))
  }
}
