apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pg-rs
  labels:
    app: pg-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pg-test
  template:
    metadata:
      labels:
        app: pg-test
    spec:
      containers:
      - name: pg-cluster
        image: postgres:14
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: password
      
