# Database Configuration
database:
  url: jdbc:mysql://localhost:3306/mybatis_cache_db
  username: app_user
  password: app_password
  driver: com.mysql.cj.jdbc.Driver

# HikariCP Connection Pool Configuration
hikari:
  maximum-pool-size: 10
  minimum-idle: 5
  connection-timeout: 30000
  idle-timeout: 600000
  max-lifetime: 1800000
  leak-detection-threshold: 60000

# MyBatis Configuration
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.entity

# Server Configuration
server:
  port: 8080
  context-path: /api

# Logging Configuration
logging:
  level:
    org.example.mapper: DEBUG
    org.mybatis.caches.caffeine: DEBUG
    com.zaxxer.hikari: INFO
    org.apache.ibatis: DEBUG