/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("me.champeau.jmh") version "0.7.2"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // Redis client
    implementation(libs.redisson)

    // Environment variables from .env file
    implementation(libs.dotenv)

    // Client-side caching
    implementation(libs.caffeine)

    // SLF4J facade with Log4j2 implementation
    implementation("org.slf4j:slf4j-api:2.0.7")
    implementation("org.apache.logging.log4j:log4j-slf4j2-impl:2.20.0")
    implementation("org.apache.logging.log4j:log4j-core:2.20.0")

    // JMH benchmarking
    implementation(libs.jmh.core)
    annotationProcessor(libs.jmh.generator.annprocess)

    // For IntelliJ JMH support
    testImplementation(libs.jmh.core)
    testAnnotationProcessor(libs.jmh.generator.annprocess)
    
    // Annotation processing for cache generation
    implementation(libs.javapoet)
    
    // Tablesaw for data analysis and plotting
    implementation(libs.tablesaw.core)
    implementation(libs.tablesaw.jsplot)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


application {
    // Define the main class for the application.
    mainClass = "org.example.BuilderExample"
}


tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()

    // Show test output
    testLogging {
        showStandardStreams = true
    }
}

tasks.withType<JavaCompile> {
    options.compilerArgs.addAll(listOf("-Xlint:processing"))
}

// Task to compile annotation processors first
val compileProcessors by tasks.registering(JavaCompile::class) {
    source = fileTree("src/main/java") {
        include("**/AutoBuilder.java", "**/BuilderProcessor.java", "**/CacheProcessor.java", "**/Cache.java", "**/CacheEnabled.java")
    }
    destinationDirectory.set(layout.buildDirectory.dir("processor-classes"))
    classpath = configurations.getByName("compileClasspath")
    
    options.compilerArgs.add("-proc:none") // Don't run annotation processing on processors themselves
    
    doLast {
        // Copy service file
        copy {
            from("src/main/resources/META-INF")
            into(layout.buildDirectory.dir("processor-classes/META-INF"))
        }
    }
}

tasks.named<JavaCompile>("compileJava") {
    dependsOn(compileProcessors)
    
    doFirst {
        // Add processor JAR to annotation processor path
        options.annotationProcessorPath = files(layout.buildDirectory.dir("processor-classes")) + configurations.getByName("compileClasspath")
    }
}
