version: "3.9"
services:
  trino:
    ports:
      - "8080:8080"
    image: "trinodb/trino:445"
    volumes:
      - trino-volume:/usr/lib/trino/etc:ro
      - trino-volume:/etc/trino/catalog
      - ./catalog/localmongo.properties:/etc/trino/catalog/localmongo.properties
  debug:
    image: "ubuntu:20.04"
    volumes:
      - trino-volume:/etc/trino
networks:
  default:
    name: trino-net

volumes:
  trino-volume:
