apiVersion: v1
kind: Pod
metadata:
  name: pg-test
  labels:
      app: pg-test
spec:
  containers:
  - name: pg-test-container
    image: postgres:14
    ports:
      - containerPort: 5432
    env:
    - name: POSTGRES_PASSWORD
      value: password