- name: Install docker engine
  shell: curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh ./get-docker.sh && rm ./get-docker.sh
- name: Add user to docker group
  shell: sudo usermod -aG docker $USER
- name: reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection
- name: Test docker installation
  shell: sudo service docker start && docker run hello-world