/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package producer_consumer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        ProducerExample prod = new ProducerExample();
        try {
            prod.main(args);
        } catch (Exception e) {
            e.printStackTrace();
            // code inside the try block
        }
    }
}
