/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;
import java.util.Comparator;

public class App {


    public String getGreeting() {
        return "Hello World!";
    }


    public static void main(String[] args) {
        MyObject[] objects = {
                new MyObject(3, 10),
                new MyObject(1, 20),
                new MyObject(5, 30),
                new MyObject(2, 40),
        };

        // Sort by x in descending order
        Arrays.sort(
                objects,
                Comparator.comparingInt((MyObject obj) -> obj.x).reversed()
        );

        int[][] lists = new int[][]{
                {1, 2},
                {-3, 2},
                {2, 3},
                {-1, 2},
        };

        Arrays.sort(lists, Comparator.comparing((int[] l) -> l[0]).reversed());

        System.out.println("sorted lists: " + Arrays.deepToString(lists));

        // Or using lambda directly
        // Arrays.sort(objects, (a, b) -> Integer.compare(b.x, a.x));

        System.out.println("sorted objects: " + Arrays.toString(objects));
        // Output: [MyObject{x=5, y=30}, MyObject{x=3, y=10}, MyObject{x=2, y=40}, MyObject{x=1, y=20}]
    }
}
