version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mybatis_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mybatis_example
      MYSQL_USER: mybatis_user
      MYSQL_PASSWORD: mybatis_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: