/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.rmi.Remote;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
		RemoteClassLoader loader = new RemoteClassLoader();
		loader.main(args);
    }
}
