[project]
name = "ray-badword-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "ray[serve]>=2.46.0",
    "torch>=2.7.0",
    "transformers>=4.51.3",
]
