apiVersion: v1
kind: Pod
metadata:
  name: hostpath-example
spec:
  containers:
  - name: example-container
    image: nginx
    volumeMounts:
    - mountPath: /data
      name: example-volume
  volumes:
  - name: example-volume
    hostPath:
      path: /tmp/
      type: DirectoryOrCreate
