# https://www.mongodb.com/community/forums/t/configure-replica-set-with-docker/212488

version: '3.8'

services:
  mongo1:
    container_name: mongo1
    hostname: mongo1
    image: mongo:7.0
    expose:
      - 27017
    ports:
      - 30001:27017
    restart: always
    networks:
      - my-db
    command: mongod --replSet myrs
  mongo2:
    container_name: mongo2
    hostname: mongo2
    image: mongo:7.0
    expose:
      - 27017
    ports:
      - 30002:27017
    restart: always
    networks:
      - my-db
    command: mongod --replSet myrs
  mongo3:
    container_name: mongo3
    hostname: mongo3
    image: mongo:7.0
    expose:
      - 27017
    ports:
      - 30003:27017
    restart: always
    networks:
      - my-db
    command: mongod --replSet myrs

  mongoinit:
    container_name: mongoinit
    image: mongo:7.0
    restart: "no"
    networks:
      - my-db
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    command: wait-for-it.sh

networks:
  my-db:
    driver: bridge
