apiVersion: v1
kind: Service
metadata:
  name: job-manager-service
spec:
  selector:
    app: manager
  ports:
    - name: manager
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
        - name: manager
          image: unknowntpo/job-manager:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "1G"
              cpu: "1000m"
          env:
          - name: RABBITMQ_HOST
            value: "rabbitmq"
          - name: RABBITMQ_PORT
            value: "5672"
